### ISSUE TITLE
Selecting card in search by card list just hides list

### ISSUE THREAD

**Issue by BanSolitude** [CorayThan/decks-of-keyforge#29]
**Describe the bug**
After selecting a card from the drop-down in the search by card section of the deck search page the drop-down disappears, but the card is not added to the search box (ie the search field remains black)
Note the cards is properly added to the query, and other actions (clicking search, clicking add card, etc) cause the card name to appear.

**To Reproduce**
1. Go to https://decksofkeyforge.com/decks
2. Click on "Cards" in left have search panel
3. Click "Add Card"
4. Click on card name input, and select "1-2 punch" (or any other card name)

**Expected behavior**
Card name is displayed in input.

**Desktop (please complete the following information):**
 - OS: both android and Windows 10
 - Browser: Chrome
 - Version: 114.0.5735.133/131.

**Comment by CorayThan** [comment]
This should be fixed.
