### ISSUE TITLE
Previous owner search not working 

### ISSUE THREAD

**Issue by mcarulli** [CorayThan/decks-of-keyforge#31]
********
This is not for reporting problems with the SAS or AERC rating of cards / decks! Use the Card change report template for that.
********

**Describe the bug**
Tried searching for decks I previously owned, and instead my search results display every deck on dok. The url correctly displays my query, but the "previously owned" checkbox unchecks upon searching. 

**To Reproduce**
1. Go to decks search
2. Click on 'previously owned' and hit search 
3. Results show all decks regardless of previous ownership 

**Expected behavior**
Only show decks I previously had marked as owned.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CorayThan** [comment]
Pushing a fix for this
