### ISSUE TITLE
Unable to search for decks for sale

### ISSUE THREAD

**Issue by mcarulli** [CorayThan/decks-of-keyforge#32]
********
This is not for reporting problems with the SAS or AERC rating of cards / decks! Use the Card change report template for that.
********

**Describe the bug**
When going to Decks > For Sale, an error message occurs and the search button keeps spinning without finding any results. 

**To Reproduce**
1. Go to any page on DoK on web or mobile
2. Click on 'Decks>For Sale' 
3. See error "There was an unexpected error making your request."

**Expected behavior**
All decks listed for sale appear

**Screenshots**
<img width="1780" alt="Screen Shot 2023-06-28 at 8 27 32 AM" src="https://github.com/CorayThan/decks-of-keyforge/assets/40010247/35dc771c-15c5-424d-98ad-b4246c40194a">

**Desktop (please complete the following information):**
 - iOS
 - Chrome
 - Version 114.0.5735.133 

**Additional context**
Similar errors occur for other searches, like "Team decks" (my team has 1000+ decks)

**Comment by CorayThan** [comment]
Should be fixed!
