### ISSUE TITLE
Some WoE Reprints Missing Old Set Data

### ISSUE THREAD

**Issue by UltimoFox** [CorayThan/decks-of-keyforge#36]
**Describe the bug**
Several cards that were reprinted in WoE are missing their previous set data in Cards of KeyForge: Legion's March, "Bubbles", Kiligog's Trench, and Sobogg's Thingamabob. There may be more examples, but those are the only ones I was able to find.

**To Reproduce**
1. Go to 'Cards of KeyForge'
2. Search all cards in all sets before WoE.
3. Some cards are not present despite being available before WoE. I was able to see the 4 mentioned above due to having Archon Arcana open with the card lists to compare side-by-side.

**Expected behavior**
I expected to see "Bubbles" appear when I was looking through DT Unfathomable cards, but it wasn't there. Then I noticed the other ones.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version 114.0.1823.43

**Comment by CorayThan** [comment]
Revised how cards work should be fixed.
