### ISSUE TITLE
"No expansion for number 609" when importing woe deck

### ISSUE THREAD

**Issue by avandever** [CorayThan/decks-of-keyforge#41]
********
This is not for reporting problems with the SAS or AERC rating of cards / decks! Use the Card change report template for that.
********

**Describe the bug**
When importing deck via MV url, this error appears, and deck is not imported into dok.

**To Reproduce**
1. Go to Decks -> Import Deck
2. Paste in deck url: https://www.keyforgegame.com/deck-details/fc7214f6-0542-49eb-a687-1fc35b8539e6
3. Click "Import to my decks"

**Expected behavior**
I expected the deck to be imported to dok, and to be redirected to the dok page for the deck.

**Screenshots**
![image](https://github.com/CorayThan/decks-of-keyforge/assets/1231665/6212ab0f-0b65-4ade-be5f-4c1e0e7971b9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave (chromium)
 - Version: 1.52.130, Chromium 114.0.5735.198 (Official Build) (64-bit)

**Comment by adamb3ard** [comment]
I also ran into this with an unchained deck: https://www.keyforgegame.com/deck-details/68072c5d-47b0-4814-b76e-0fe802255f87

**Comment by zachzombie** [comment]
I also ran into this with an unchained deck: https://www.keyforgegame.com/deck-details/a5304d9d-0404-4fb9-8c93-979fe0b0c752

**Comment by NightFury1919** [comment]
I'm having this issue as well. My first deck from WOE came with four mavericks, three of which were legacy cards. On DoK, there's only 21 decks like that currently. Could it be related to the cards in my deck? The second deck I bought registered just fine.

**Comment by shadowfrillz** [comment]
Same here:
Here is the link to the deck: https://www.keyforgegame.com/deck-details/db43a294-015f-45ec-bd1c-1916bf6dffc0

**Comment by davidsmithdc** [comment]
I have two Unchained decks that produce the same error when attempting to import them.

https://www.keyforgegame.com/deck-details/76bcdfcd-4b78-41b3-8081-34ea6235af83
https://www.keyforgegame.com/deck-details/aaffb852-7c25-41d1-b06f-93242e9befb3

**Comment by CorayThan** [comment]
This should all be fixed now. Please create a new ticket if there are further issues!
