### ISSUE TITLE
Cards API / wrong images links

### ISSUE THREAD

**Issue by garrigou** [CorayThan/decks-of-keyforge#42]
**Describe the bug**
When I use https://decksofkeyforge.com/public-api/v1/cards there are some errors for the links of the images. For example :  Groke Brobnar (WORLDS_COLLIDE) the link of the image is https://cdn.keyforgegame.com/media/card_front/en/452_008_C9QCC7MWQW8G_en.png but it did not exists...

**Screenshots**
file_get_contents(https://cdn.keyforgegame.com/media/card_front/en/452_008_C9QCC7MWQW8G_en.png): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known

Have I missed something ?

**Comment by CorayThan** [comment]
I've changed entirely how that endpoint works and it should no longer display image links from master vault.
