### ISSUE TITLE
Deck Shows Value for Token when a Token Cannot be Created

### ISSUE THREAD

**Issue by reddtrain** [CorayThan/decks-of-keyforge#44]
********
This is not for reporting problems with the SAS or AERC rating of cards / decks! Use the Card change report template for that.
********

**Describe the bug**
When a deck with a token has no way to actually make that token, it's still shown with its value under the house listing.

**To Reproduce**
https://decksofkeyforge.com/decks/ca207ac4-493c-4f5e-8892-06658afd4113

**Expected behavior**
I expected to not see a value present for the token in the house SAS preview.

**Additional context**
I'm guessing this is a complete and utter corner case, but I'm submitting it just in case it's more than that.

**Comment by CorayThan** [comment]
Yeah, this is a weird thing and I'd say it's more a master vault problem than my problem. SAS is still correct.
