### ISSUE TITLE
Dark Mode - Cannot read text on offers page

### ISSUE THREAD

**Issue by avandever** [CorayThan/decks-of-keyforge#48]
**Description**
When using Dark Mode, text on the page https://decksofkeyforge.com/my-dok/offers is the same color as the background, making it impossible to read.

**To Reproduce**
1. Go to https://decksofkeyforge.com/my-dok/my-profile .
2. Click to toggle Dark Mode to Enable.
3. Click Save.
4. Go to https://decksofkeyforge.com/my-dok/offers .
5. See that text is not visible.

**Expected behavior**
Text should be high contrast.

**Screenshots**
![image](https://github.com/CorayThan/decks-of-keyforge/assets/1231665/25f08dbd-5aa2-431e-8721-f6f5ba0a75b8)
Compare with normal mode:
![image](https://github.com/CorayThan/decks-of-keyforge/assets/1231665/56351814-0609-4395-8923-5e9c98403dd2)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Brave

**Smartphone (please complete the following information):**
 - Version v1.58.135, Chromium 117.0.5938.140

**Comment by CorayThan** [comment]
Fixed
