### ISSUE TITLE
Card "Archon's Callback" is no longer associated with DT

### ISSUE THREAD

**Issue by reddtrain** [CorayThan/decks-of-keyforge#50]
**Describe the bug**
When I search my decks for copies of Archon's Callback, I don't find anything. I have found decks that do have it. When I search all decks for Archon's Callback, it only finds VM decks.

**To Reproduce**
In the deck search screen, type "Archon's Callback" under the Cards > Add Card, then press Search.

**Expected behavior**
I expect DT decks with one or more copies of Archon's Callback to show up. For example, when I search my own decks, I expect https://decksofkeyforge.com/decks/50ffb0a2-bede-46fd-adb5-6d3679d74143 to show up with that search criteria.

**Desktop (please complete the following information):**
Windows 10
Chrome
119.0.6045.125

**Comment by CorayThan** [comment]
I rewrote how cards work on DoK to fix issues like this.
