### ISSUE TITLE
new decks missing or delayed

### ISSUE THREAD

**Issue by fuglesport** [CorayThan/decks-of-keyforge#51]
I added 12 new decks of Worlds Collide to my Master Vault november 26th, and they still don't show in DoK.

Are they missing in the database, or is there a significant delay?

They entered Master Vault just fine:
The Primitive Warmaster of Lancarock
Knudsen the Openly Dismal
Talong Florus, the Snickering and Extinct
Ragnarsdottir, Laserwater’s Scammer
Fricco, Primes Shoppe Bureaucrat
Y. G. Headbite of the Yellow Theater
X. Rumrunner, Tilligill’s Annual Firefighter
V. Q. Laserlight of the Pessimistic Valley
“Zeke” Goliath, Villa Architect
Gunhild, Monument First Mate
The Voracious Cutthroat of Westbog
Draven, Icencourt Scamp

Best regards, Martin

**Comment by CorayThan** [comment]
I had imports turned off for a while. You can always manually import them.

**Comment by fuglesport** [comment]
Hi

I realized that later, so I'm all up-to-date now. Thanks, and great work! 🙂

best regards
Martin
________________________________
Fra: Nova ***@***.***>
Sendt: 9. februar 2024 03:09
Til: CorayThan/decks-of-keyforge ***@***.***>
Cc: fuglesport ***@***.***>; Author ***@***.***>
Emne: Re: [CorayThan/decks-of-keyforge] new decks missing or delayed (Issue #51)


I had imports turned off for a while. You can always manually import them.
