### ISSUE TITLE
Optional assigning SAS to token creators rather than tokens

### ISSUE THREAD

**Issue by abeautifuljune** [CorayThan/decks-of-keyforge#52]
I would suggest allowing users to toggle an option to either display token AERC assigned to the tokenXnumber of tokens OR assigned to the token generator. Currently the only mode of display is assigning the AERC to the token itself.

It would assist in understanding where the power in your deck comes from, in the process improving your understanding of how strong each house is. This would improve the ability to identify pods for alliance use (lol stepchild format fr) It may be simply more readable fora number of players I've spoken to who currently find the lumped aerc clouds the view of the deck.

thank you byyye 🫶
june

**Comment by CorayThan** [comment]
While I agree this would be nice in some ways. I think the current way is the best default and it would require too much UI + code complexity to support an alternative way of displaying this.
