### ISSUE TITLE
Displayed SAS does not match SAS according to search and api

### ISSUE THREAD

**Issue by avandever** [CorayThan/decks-of-keyforge#53]
********
This is not for reporting problems with the SAS or AERC rating of cards / decks! Use the Card change report template for that.
********

**Describe the bug**
For at least one deck (https://decksofkeyforge.com/decks/5cfb03fb-66b8-4bd7-8e1b-ad896bed23a8), Sas rating displayed in the web uit does not match what is reported via the api SasRating field, nor what is used for search.

**To Reproduce**
1. Go to https://decksofkeyforge.com/decks/5cfb03fb-66b8-4bd7-8e1b-ad896bed23a8
2. Read "83 SAS"
3. Go to https://decksofkeyforge.com/public-api/v3/decks/5cfb03fb-66b8-4bd7-8e1b-ad896bed23a8
4. Search for "SasRating", see 82.
5. Try search for name with min sas 83 (https://decksofkeyforge.com/decks?constraints=sasRating_MIN_83&title=veldrix)
6. See no deck displayed

**Expected behavior**
Sas rating in api should match what is displayed in web ui.
Search results should be based on same number as api and web ui.

**Screenshots**
![web ui](https://github.com/CorayThan/decks-of-keyforge/assets/1231665/f87fba91-fee3-45b2-9566-5fdabf9654c2)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Brave (Chromium)
 - Version 1.61.109 Chromium 120.0.6099.144, 64-bit

**Additional context**
API Json:
`{"deck":{"deckType":"STANDARD","id":23960189,"keyforgeId":"5cfb03fb-66b8-4bd7-8e1b-ad896bed23a8","expansion":"WINDS_OF_EXCHANGE","name":"Z. D. Veldrixhee of the Normcore Domicile","creatureCount":12,"actionCount":16,"artifactCount":6,"upgradeCount":2,"expectedAmber":21.7325,"amberControl":18.7075,"creatureControl":13.91875,"artifactControl":3.0,"efficiency":0.45999999999999996,"effectivePower":108,"creatureProtection":0.5,"disruption":-2.0,"other":1.7650000000000001,"aercScore":65,"previousSasRating":0,"previousMajorSasRating":0,"aercVersion":43,"sasRating":82,"synergyRating":17,"antisynergyRating":0,"metaScores":{},"efficiencyBonus":0.0,"totalPower":72,"cardDrawCount":2,"rawAmber":11,"totalArmor":1,"lastSasUpdate":"2023-08-02","sasPercentile":99.61011075592376,"hasOwnershipVerification":true,"housesAndCards":[{"house":"Brobnar","cards":[{"cardTitle":"One Stood Against Many","rarity":"Rare","legacy":false,"maverick":true,"anomaly":false,"enhanced":false},{"cardTitle":"Overrun","rarity":"Uncommon","legacy":false,"maverick":false,"anomaly":false,"enhanced":true,"bonusAember":0,"bonusCapture":0,"bonusDamage":1,"bonusDraw":0},{"cardTitle":"Pound","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":true,"bonusAember":0,"bonusCapture":0,"bonusDamage":0,"bonusDraw":1},{"cardTitle":"Ragnarok Prep","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Rant and Rive","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Relentless Assault","rarity":"Uncommon","legacy":true,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Stratosmack","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":true,"bonusAember":0,"bonusCapture":0,"bonusDamage":1,"bonusDraw":0},{"cardTitle":"Vow of Blood","rarity":"Uncommon","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Bumpsy","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":true,"bonusAember":0,"bonusCapture":0,"bonusDamage":1,"bonusDraw":0},{"cardTitle":"Frost Giant","rarity":"Rare","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Jarl Svend","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Shock Herder","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":false}]},{"house":"Ekwidon","cards":[{"cardTitle":"Auction Off","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Auction Off","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Closed-Door Negotiation","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Market Crash","rarity":"Uncommon","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Exo-shell System","rarity":"Uncommon","legacy":false,"maverick":false,"anomaly":false,"enhanced":true,"bonusAember":1,"bonusCapture":0,"bonusDamage":1,"bonusDraw":0},{"cardTitle":"Puzzling Trinket","rarity":"Uncommon","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Tourist Trap","rarity":"Rare","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Belligerent Guard","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Dthoshră, Recruiter","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Shrewd Investor","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Tya-Arhĭ, Esquire","rarity":"Uncommon","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Niffle Paw","rarity":"Uncommon","legacy":false,"maverick":false,"anomaly":false,"enhanced":false}]},{"house":"Mars","cards":[{"cardTitle":"Braindart","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Psychic Network","rarity":"Uncommon","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Psychic Network","rarity":"Uncommon","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Space Invaders","rarity":"Uncommon","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Mk.2 Generator","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Mk.2 Generator","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Mk.2 Generator","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Ether Spider","rarity":"Uncommon","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Glylyx Weaponsmith","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Myx, the Tallminded","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":false},{"cardTitle":"Myx, the Tallminded","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":true,"bonusAember":1,"bonusCapture":0,"bonusDamage":0,"bonusDraw":0},{"cardTitle":"Ironyx Propaganda","rarity":"Common","legacy":false,"maverick":false,"anomaly":false,"enhanced":false}]}],"dateAdded":"2023-08-03","tokenInfo":{"id":"94209e50-cca6-4953-be2e-df27b544eb31","name":"Grunt","house":"Mars"}},"sasVersion":43}
`

**Comment by CorayThan** [comment]
I switched it to never return the saved SAS scores, so they should be more consistent now.
