### ISSUE TITLE
Tags not working

### ISSUE THREAD

**Issue by ShooterSK** [CorayThan/decks-of-keyforge#54]
I have tags assigned to decks, that have always worked. Currently all my tags return a message "Sorry no decks match your search criteria".

Thx

********
This is not for reporting problems with the SAS or AERC rating of cards / decks! Use the Card change report template for that.
********

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CorayThan** [comment]
This should be fixed.

**Comment by ShooterSK** [comment]
Thanks Nova, it is.

Steve
