### ISSUE TITLE
Malfunction on SAS calculator on new decks

### ISSUE THREAD

**Issue by guilleg96** [CorayThan/decks-of-keyforge#56]
********
This is not for reporting problems with the SAS or AERC rating of cards / decks! Use the Card change report template for that.
********

**Describe the bug**
I can't calculate de SAS score of new decks, if I try it apears a message in red saying Card string was blank! and afterwards says the name of the deck

**To Reproduce**
1. Go to your keyforge deck on the oficcioal weppage
2. Click on the URL of the deck and copy it
3. Paste on import Deck 

**Expected behavior**
Card string was blank! *Deck tittle*

**Screenshots**
![Captura de pantalla 2024-02-02 a las 9 43 28](https://github.com/CorayThan/decks-of-keyforge/assets/158562344/b92f6430-2377-4cbe-b279-a6420d0e8573)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CorayThan** [comment]
This should be fixed.
