### ISSUE TITLE
Choose a random deck button

### ISSUE THREAD

**Issue by Hasame180** [CorayThan/decks-of-keyforge#61]
*********************************************
First search DoK features to make sure this is not a duplicate request.
https://github.com/CorayThan/decks-of-keyforge/issues?q=label%3Adok-feature+
*********************************************

**Describe what you would like changed or added.**

Add a button to the filter sidebar that chooses a random deck from those currently displayed.
![DoK Random button](https://github.com/CorayThan/decks-of-keyforge/assets/172694176/f34b6ece-991f-4914-b2d3-65f2bfe0575d)

**Describe how this change would improve your experience as a KeyForge player.**

People have asked for a feature that helps determine which deck from their collection to randomly play in TCO, or bring to local game night. I think this would assist in choosing which decks to play. Also, some decks that would never see play may get a chance to see the light!

**Comment by Hasame180** [comment]
I just realized this is very similar to the "I'm Feeling Lucky" button at Google, so maybe name it that

**Comment by CorayThan** [comment]
This is tougher to implement than you'd expect, unfortunately, and I'm not planning on adding this feature.
